### PR TITLE
Add installation commands

### PR DESCRIPTION
**Pull request by Botspot**
Tested and working. This is so much faster and simpler than the painstakingly long [video tutorial](https://www.youtube.com/watch?v=pEhutXW-ZJU).

### CODE REVIEW

**Comment by boomerangos** [comment]
wget https://github.com/boomerangos/Cracked-Launcher/raw/master/crackedlauncherVer1.1.jar

**Comment by Botspot** [comment]
I'm sorry, why did you send me that command?  
Do you know what a pull request is?

**Comment by boomerangos** [comment]
done

**Comment by Botspot** [comment]
Haha!
You could have just clicked "Merge this Pull Request", but I suppose copying and pasting my text will work too.

**Pull request closed without merging**
